import { jsPDF } from "jspdf";
import { ItineraryPlan, FlightOption, HotelOption, Language } from "../types";

// Helper to draw a dashed line
function drawDashedLine(doc: jsPDF, x1: number, y1: number, x2: number, y2: number, dashLength = 2, gapLength = 2) {
  const dx = x2 - x1;
  const dy = y2 - y1;
  const distance = Math.sqrt(dx * dx + dy * dy);
  const numDashes = Math.floor(distance / (dashLength + gapLength));
  const xStep = dx / numDashes;
  const yStep = dy / numDashes;

  for (let i = 0; i < numDashes; i++) {
    const startX = x1 + i * xStep;
    const startY = y1 + i * yStep;
    const endX = startX + (dashLength / (dashLength + gapLength)) * xStep;
    const endY = startY + (dashLength / (dashLength + gapLength)) * yStep;
    doc.line(startX, startY, endX, endY);
  }
}

// -------------------------------------------------------------------------
// 1. GENERATE FULL TOURISM ITINERARY PDF SPECIALIST
// -------------------------------------------------------------------------
export function generateItineraryPDF(plan: ItineraryPlan, lang: Language) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const isAr = lang === "ar";
  
  // PAGE 1: COVER PAGE
  // Draw beautiful violet gradient top block
  doc.setFillColor(124, 58, 237); // #7c3aed
  doc.rect(0, 0, 210, 110, "F");

  // Cover text
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("GO WITH AHMED TRAVEL PLANNER", 20, 45);
  
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.text(isAr ? "دليل السفر السياحي المتكامل" : "Your Tailored International Tourism File", 20, 60);

  doc.setFontSize(14);
  doc.setFillColor(255, 255, 255);
  doc.setTextColor(124, 58, 237);
  // Elegant Badge
  doc.rect(20, 72, 75, 12, "F");
  doc.text(`DESTINATION: ${plan.country.toUpperCase()}`, 24, 80);

  // Metadata block in white area
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(isAr ? "معلومات الرحلة الأساسية" : "CRUCIAL VOYAGE METADATA", 20, 130);
  
  doc.setFont("helvetica", "normal");
  doc.text(isAr ? `الوجهة المستهدفة: ${plan.country}` : `Destination Territory: ${plan.country}`, 20, 140);
  doc.text(isAr ? `عدد أيام البرنامج: ${plan.duration} أيام تفصيلية` : `Duration Matrix: ${plan.duration} Full Days Scheduled`, 20, 148);
  doc.text(isAr ? "مستوى الدقة: دقة متناهية بالثانية" : "Precision Level: Coordinated Second-by-Second", 20, 156);
  
  // Accent lines
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(1);
  doc.line(20, 120, 70, 120);

  // Overview box with dynamic height to prevent text overflow
  const overviewLines = doc.splitTextToSize(plan.overview, 160);
  const overviewHeight = 18 + (overviewLines.length * 4.8);
  doc.setFillColor(248, 250, 252);
  doc.rect(20, 170, 170, overviewHeight, "F");
  doc.setDrawColor(226, 232, 240);
  doc.rect(20, 170, 170, overviewHeight, "S");
  doc.setFont("helvetica", "bold");
  doc.setTextColor(124, 58, 237);
  doc.text(isAr ? "نبذة الوجهة وسيناريو الرحلة" : "VIBE & HIGHLIGHTS SYNOPSIS", 25, 180);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(overviewLines, 25, 188);

  // Footer cover
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Go with Ahmed Travel Engine on " + new Date().toLocaleDateString(), 20, 275);
  doc.text("Page 1 of " + (plan.days.length + 2), 180, 275);

  // PAGES 2+: DETAILED DAYS TIMELINE
  plan.days.forEach((day, index) => {
    doc.addPage();
    
    // Header
    doc.setFillColor(124, 58, 237);
    doc.rect(0, 0, 210, 22, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(`DAY ${day.dayNumber}: ${day.title}`, 15, 14);

    let currentY = 35;

    // Daily schedule sub-header
    doc.setTextColor(124, 58, 237);
    doc.setFontSize(12);
    doc.text(isAr ? "برنامج الأنشطة المفصل بالساعة والترتيب:" : "EXACT TIMELINE & ACTIVITY ROSTER:", 15, currentY);
    currentY += 8;

    // Draw activities
    day.activities.forEach((act) => {
      // Draw timeframe pill
      doc.setFillColor(245, 243, 255);
      doc.rect(15, currentY - 4, 25, 6, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(124, 58, 237);
      doc.text(act.time, 18, currentY);

      // Activity Title
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(act.title, 45, currentY);

      // Location annotation below
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(`@ ${act.location}`, 45, currentY + 4.5);

      // Description split
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      const descLines = doc.splitTextToSize(act.description, 135);
      doc.text(descLines, 45, currentY + 9);

      // Line spacer
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.3);
      doc.line(15, currentY + 16, 195, currentY + 16);

      currentY += Math.max(22, 11 + descLines.length * 4.5);
    });

    // Curated Dining for this day
    if (day.restaurants && day.restaurants.length > 0) {
      if (currentY > 215) {
        doc.addPage();
        currentY = 35;
      } else {
        currentY += 5;
      }

      let totalRestaurantsHeight = 15;
      day.restaurants.forEach((rest) => {
        const tipLines = doc.splitTextToSize(`${isAr ? "الطبق المميز: " : "Tip: "}${rest.tip}`, 165);
        totalRestaurantsHeight += 6 + tipLines.length * 4.5;
      });
      doc.setFillColor(248, 250, 252);
      doc.rect(15, currentY, 180, totalRestaurantsHeight, "F");
      doc.setDrawColor(226, 232, 240);
      doc.rect(15, currentY, 180, totalRestaurantsHeight, "S");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(124, 58, 237);
      doc.text(isAr ? "ترشيحات المطاعم الموصى بها لهذا اليوم:" : "RECOMMENDED DINING PLACES FOR TODAY:", 20, currentY + 8);

      let restY = currentY + 16;
      day.restaurants.forEach((rest) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(15, 23, 42);
        doc.text(`${rest.name} (${rest.type})`, 20, restY);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(71, 85, 105);
        const tipText = `${isAr ? "الطبق المميز: " : "Tip: "}${rest.tip}`;
        const tipLines = doc.splitTextToSize(tipText, 165);
        doc.text(tipLines, 20, restY + 4.5);

        restY += 6 + tipLines.length * 4.5;
      });
    }

    // Footers
    doc.setFontSize(8.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Go with Ahmed Travel Guide - ${plan.country.toUpperCase()}`, 15, 285);
    doc.text(`Page ${index + 2} of ${plan.days.length + 2}`, 180, 285);
  });

  // FINAL PAGE: ESSENTIAL REINFORCEMENTS & SECURITY TIPS
  doc.addPage();
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, 210, 22, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(isAr ? "إرشادات السفر العامة وتنسيقات الأمان" : "ESSENTIAL REINFORCEMENTS & TRAVEL SECURITY", 15, 14);

  let tipsY = 40;
  doc.setTextColor(124, 58, 237);
  doc.setFontSize(12);
  doc.text(isAr ? "قائمة نصائح خبراء GO WITH AHMED للسياحة:" : "THE OFFICIAL TRAVEL GUIDELINES & PRECAUTIONS:", 15, tipsY);
  tipsY += 12;

  plan.essentialTips.forEach((tip, tIdx) => {
    // Left border block
    doc.setFillColor(124, 58, 237);
    doc.rect(15, tipsY - 4, 2, 16, "F");

    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(`${isAr ? "توجيه" : "ADVICE"} #${tIdx + 1}`, 20, tipsY);

    doc.setTextColor(71, 85, 105);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    const tipLines = doc.splitTextToSize(tip, 165);
    doc.text(tipLines, 20, tipsY + 5);

    tipsY += Math.max(22, 10 + tipLines.length * 4.5);
  });

  // Custom QR Code Box decoration
  doc.setFillColor(248, 250, 252);
  doc.rect(15, tipsY + 10, 180, 45, "F");
  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(0.4);
  doc.rect(15, tipsY + 10, 180, 45, "S");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(124, 58, 237);
  doc.text(isAr ? "رمز تفعيل الرحلة - تطبيق GO WITH AHMED والتحقق" : "GO WITH AHMED VERIFICATION QR-CODE & CLIENT FILE", 25, tipsY + 20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(isAr 
    ? "يمكن مسح هذا المستند في مطارات العبور للتحقق من البرنامج المخطط ومطابقته لتأشيرة السياحة الإليكترونية."
    : "This layout forms an offline travel guide matching standard Schengen and Asian travel file requirements.",
    25, tipsY + 28
  );
  
  // Simulated small structural QR Code
  doc.setDrawColor(0, 0, 0);
  doc.setFillColor(15, 23, 42);
  doc.rect(160, tipsY + 15, 25, 25, "F");
  // White patterns
  doc.setFillColor(255, 255, 255);
  doc.rect(163, tipsY + 18, 7, 7, "F");
  doc.rect(175, tipsY + 18, 7, 7, "F");
  doc.rect(163, tipsY + 30, 7, 7, "F");
  // Mini dots
  doc.setFillColor(0, 0, 0);
  doc.rect(165, tipsY + 20, 3, 3, "F");
  doc.rect(177, tipsY + 20, 3, 3, "F");
  doc.rect(165, tipsY + 32, 3, 3, "F");

  // Output
  doc.save(`GoWithAhmed_Travel_Plan_${plan.country.replace(/\s+/g, "_")}.pdf`);
}

// -------------------------------------------------------------------------
// 2. GENERATE DUMMY FLIGHT BOARDING PASS TICKET
// -------------------------------------------------------------------------
export function generateFlightTicketPDF(flight: FlightOption, passenger: any, lang: Language) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Helper to replace all non-ASCII characters & keep clean English
  const cleanAscii = (str: string, fallback: string = ""): string => {
    if (!str) return fallback;
    let cleaned = str.replace(/[^\x00-\x7F]/g, "").trim();
    cleaned = cleaned.replace(/\/\s*/g, " ").replace(/\(\s*\)/g, "").trim();
    // collapse multiple spaces into one
    cleaned = cleaned.replace(/\s+/g, " ");
    return cleaned || fallback;
  };

  const safeName = cleanAscii(passenger.name, "PASSENGER").toUpperCase();
  const safePassport = cleanAscii(passenger.passport, "X0000000").toUpperCase();
  const safeFrom = cleanAscii(passenger.from, "CAI").toUpperCase();
  const safeTo = cleanAscii(passenger.to, "LHR").toUpperCase();
  const safeNationality = cleanAscii(passenger.nationality, "EGYPTIAN").toUpperCase();
  const safeDob = cleanAscii(passenger.dob, "1996-05-15");
  const safeFlightNo = cleanAscii(passenger.flightNoCustom || flight.flightNo, "MS 777").toUpperCase();
  const safePnr = cleanAscii(passenger.pnrCode || "ER89WX", "ER89WX").toUpperCase();
  const safeTicketNum = cleanAscii(passenger.ticketNum || "077-1092837264", "077-1092837264");
  const safeAircraft = cleanAscii(passenger.aircraftType || "BOEING 777", "BOEING 777-300ER").toUpperCase();
  const safeDepTerminal = cleanAscii(passenger.depTerminal || "TERMINAL 3", "TERMINAL 3").toUpperCase();
  const safeArrTerminal = cleanAscii(passenger.arrTerminal || "TERMINAL 2", "TERMINAL 2").toUpperCase();
  const safeBaggage = cleanAscii(passenger.baggage || "2 PIECES", "2 PIECES (23KG EACH) + 1 CABIN BAG (7KG)").toUpperCase();
  
  // Custom cleaning for seat
  let safeSeat = cleanAscii(passenger.seat, "14K").toUpperCase();
  if (safeSeat.includes("14A")) safeSeat = "14A (WINDOW)";
  else if (safeSeat.includes("14K")) safeSeat = "14K (WINDOW)";
  else if (safeSeat.includes("12D")) safeSeat = "12D (AISLE)";
  else if (safeSeat.includes("15C")) safeSeat = "15C (AISLE)";
  else if (safeSeat.includes("10E")) safeSeat = "10E (MIDDLE)";
  else safeSeat = safeSeat.replace(/WINDOW|AISLE|MIDDLE/gi, "").trim() || "14K (WINDOW)";

  // Custom cleaning for flight.stops
  let stopsStr = String(flight.stops || "").toLowerCase();
  let safeStops = "DIRECT NON-STOP";
  if (stopsStr.includes("1") || stopsStr.includes("one") || stopsStr.includes("stop") || stopsStr.includes("transit") || stopsStr.includes("توقف")) {
    safeStops = "1 STOP (TRANSIT)";
  } else {
    safeStops = "DIRECT NON-STOP";
  }

  // Color Themes
  const navyDark = { r: 15, g: 23, b: 42 }; // #0f172a
  const skyTheme = { r: 2, g: 132, b: 199 }; // #0284c7
  const borderGrey = { r: 226, g: 232, b: 240 }; // #e2e8f0
  const emeraldStamp = { r: 22, g: 163, b: 74 }; // #16a34a

  // Top header stripe with "Go with Ahmed" logo banner
  doc.setFillColor(navyDark.r, navyDark.g, navyDark.b);
  doc.rect(15, 15, 180, 24, "F");

  // Logo & System header
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("GO WITH AHMED TRAVELS", 22, 25);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(200, 220, 240);
  doc.text("GLOBAL TRAVEL ARCHITECTS & FLIGHT COORDINATORS", 22, 30);

  // E-Ticket Right aligned info
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("ELECTRONIC E-TICKET RECEIPT", 125, 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.text("PASSENGER VOUCHER & ITINERARY", 125, 29);

  // BOOKING REFERENCE / PNR STYLED HIGHLIGHT BOX
  doc.setFillColor(240, 249, 255); // #f0f9ff
  doc.setDrawColor(186, 230, 253); // #bae6fd
  doc.rect(15, 45, 180, 22, "FD");

  // Label PNR
  doc.setTextColor(3, 105, 161);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("BOOKING REFERENCE (PNR)", 22, 52);
  doc.setFont("courier", "bold");
  doc.setFontSize(15);
  doc.setTextColor(3, 105, 161);
  doc.text(safePnr, 22, 60);

  // Status block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text("RESERVATION STATUS", 100, 52);
  doc.setTextColor(emeraldStamp.r, emeraldStamp.g, emeraldStamp.b);
  doc.setFontSize(12);
  doc.text("CONFIRMED (OK)", 100, 60);

  // Ticket Code
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("ELECTRONIC TICKET NO.", 148, 52);
  doc.setFont("courier", "bold");
  doc.setFontSize(10.5);
  doc.text(safeTicketNum, 148, 60);

  // 1. PASSENGER INFORMATION DATABASE
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.text("1. PASSENGER RECORD PROFILE (INTERNATIONAL TRANSIT)", 15, 80);
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.setLineWidth(0.4);
  doc.line(15, 82, 195, 82);

  let py = 88;
  // Columns for passenger metadata
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("PASSENGER COORD NAME", 18, py);
  doc.text("PASSPORT NUMBER", 78, py);
  doc.text("NATIONALITY / ORIGIN", 138, py);

  py += 5.5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text(safeName, 18, py);
  doc.text(safePassport, 78, py);
  doc.text(safeNationality, 138, py);

  py += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("DATE OF BIRTH", 18, py);
  doc.text("ISSUING SYSTEM", 78, py);
  doc.text("GDS VALIDATION", 138, py);

  py += 5.5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text(safeDob, 18, py);
  doc.text("GO WITH AHMED SYSTEMS", 78, py);
  doc.setTextColor(emeraldStamp.r, emeraldStamp.g, emeraldStamp.b);
  doc.text("VERIFIED ACTIVE", 138, py);

  // 2. FLIGHT ITINERARY DATABASE
  py += 15;
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.text("2. COMPREHENSIVE FLIGHT VOYAGE ITINERARY", 15, py);
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.line(15, py + 2, 195, py + 2);

  // Frame details card
  let cardY = py + 6;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.rect(15, cardY, 180, 78, "D");

  // Airline Header inside card
  doc.setFillColor(248, 250, 252);
  doc.rect(15.2, cardY + 0.2, 179.6, 12, "F");
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.line(15, cardY + 12, 195, cardY + 12);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.text(`${flight.airline.toUpperCase()} COORD OUTBOUND VECTOR`, 20, cardY + 8);

  // Stamp FLIGHT OK
  doc.setFillColor(236, 253, 245);
  doc.setDrawColor(167, 243, 208);
  doc.rect(145, cardY + 2.5, 42, 7, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(4, 120, 87);
  doc.text("FLIGHT STATUS: CONFIRMED", 148, cardY + 7.2);

  // Inside card left columns: flight details
  let cy = cardY + 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("FLIGHT RUN", 20, cy);
  doc.text("AIRCRAFT EQUIPMENT", 20, cy + 12);
  doc.text("CABIN CLASS", 20, cy + 24);
  doc.text("ASSIGNED SEAT", 20, cy + 36);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.text(safeFlightNo, 20, cy + 5);
  doc.setFontSize(9);
  doc.text(safeAircraft, 20, cy + 17);
  doc.text(flight.classStyle.toUpperCase() || "ECONOMY", 20, cy + 29);
  doc.setFontSize(11.5);
  doc.setTextColor(skyTheme.r, skyTheme.g, skyTheme.b);
  doc.text(safeSeat, 20, cy + 41);

  // Vertical line separator at card
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.line(75, cardY + 12, 75, cardY + 78);

  // Right column: Outbound routing
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("DEPARTURE COORDINATES (OUT)", 80, cy);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11.5);
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.text(safeFrom, 80, cy + 5);
  doc.setFontSize(9.5);
  doc.setTextColor(skyTheme.r, skyTheme.g, skyTheme.b);
  doc.text(safeDepTerminal, 80, cy + 11);
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text(`DATE: ${passenger.departDate}  -  TIME: ${flight.departureTime}`, 80, cy + 17);

  // Arrival
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text("ARRIVAL COORDINATES (IN)", 80, cy + 28);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11.5);
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.text(safeTo, 80, cy + 33);
  doc.setFontSize(9.5);
  doc.setTextColor(skyTheme.r, skyTheme.g, skyTheme.b);
  doc.text(safeArrTerminal, 80, cy + 39);
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text(`DATE: ${passenger.departDate}  -  TIME: ${flight.arrivalTime}`, 80, cy + 45);

  // Direct label
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`FLIGHT SPECS: ${safeStops}`, 80, cy + 53);

  // 3. BAGGAGE LIMITATIONS AND COMPLIANCE RULES
  py = cardY + 86;
  doc.setTextColor(navyDark.r, navyDark.g, navyDark.b);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.text("3. BAGGAGE ALLOWANCE & PASSENGER INFORMATION", 15, py);
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.line(15, py + 2, 195, py + 2);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text("CHECKED BAG ALLOWANCE:", 18, py + 8);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  const baggageLines = doc.splitTextToSize(safeBaggage, 115);
  doc.text(baggageLines, 75, py + 8);

  const baggageHeightCount = baggageLines.length;
  let cabinY = py + 8 + (baggageHeightCount * 4.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text("CABIN HAND LUGGAGE LIMIT:", 18, cabinY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  const cabinLines = doc.splitTextToSize("1 PIECE OVERHEAD BAG (MAX 7KG) + 1 PERSONAL ITEM INCLUDED", 115);
  doc.text(cabinLines, 75, cabinY);

  let warningY = cabinY + (cabinLines.length * 4.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const warningLines = doc.splitTextToSize("* Check-in closes exactly 60 minutes before departure. High-fidelity verification simulation managed securely.", 175);
  doc.text(warningLines, 18, warningY);

  // BOTTOM SIMULATED BARCODE/STAMP CHECK AREA
  let footerBoxY = py + 26;
  doc.setFillColor(248, 250, 252);
  doc.rect(15, footerBoxY, 180, 22, "F");
  doc.setDrawColor(borderGrey.r, borderGrey.g, borderGrey.b);
  doc.rect(15, footerBoxY, 180, 22, "S");

  // Generate barcodes
  let barcodeX = 22;
  doc.setFillColor(0, 0, 0);
  for (let i = 0; i < 48; i++) {
    const barWidth = Math.random() > 0.45 ? 0.9 : 0.4;
    doc.rect(barcodeX, footerBoxY + 3, barWidth, 11, "F");
    barcodeX += barWidth + (Math.random() > 0.5 ? 0.5 : 0.8);
  }

  doc.setFont("courier", "normal");
  doc.setFontSize(6.5);
  doc.text(`*GDS-REGISTERED GO WITH AHMED SYSTEM VALIDATION ID: ${safePnr}*`, 22, footerBoxY + 18);

  // Digital secure seal stamp
  doc.setDrawColor(navyDark.r, navyDark.g, navyDark.b);
  doc.setLineWidth(0.3);
  doc.circle(170, footerBoxY + 11, 8, "S");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(4.5);
  doc.text("APPROVED", 164.2, footerBoxY + 10);
  doc.setFontSize(4.5);
  doc.text("GO WITH AHMED", 163.7, footerBoxY + 13.5);

  // Absolute page numbering and legality fine print
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.8);
  doc.setTextColor(148, 163, 184);
  const legalLines = doc.splitTextToSize("© 2026 Go with Ahmed Airline Distribution Systems. Generated on behalf of passenger matching official GDS registries perfectly. For simulation visa and flights verification purposes only.", 180);
  doc.text(legalLines, 15, 285);

  // Save pdf
  doc.save(`GoWithAhmed_E_Ticket_${passenger.name.replace(/\s+/g, "_")}.pdf`);
}

// -------------------------------------------------------------------------
// 3. GENERATE HOTEL BOOKING CHECK-IN VOUCHER
// -------------------------------------------------------------------------
// Helper to ensure any input is converted to clean English characters and avoids any Arabic/Unicode rendering issues in standard jsPDF Helvetica
function ensureEnglish(text: string | null | undefined): string {
  if (!text) return "";
  const str = String(text).trim();

  const translationsMap: { [key: string]: string } = {
    // Hotel names map
    "منتجع وفندق رويال بالاس الفاخر": "Grand Palace Royal Inn & Resort",
    "فندق ساكورا بوتيك للفنون": "Sakura Boutique Art Space",
    "شقق أوريانتل هافن السكنية الراقية": "Oriental Haven Luxury Suites",
    "فندق داما روز دمشق البانورامي": "Dama Rose Hotel Damascus",
    "فندق فور سيزونز دمشق": "Four Seasons Hotel Damascus",
    "فندق شيراتون دمشق التاريخي": "Sheraton Damascus Hotel",

    // Common cities/countries
    "روما": "Rome",
    "باريس": "Paris",
    "لندن": "London",
    "القاهرة": "Cairo",
    "مصر": "Egypt",
    "إيطاليا": "Italy",
    "فرنسا": "France",
    "بريطانيا": "United Kingdom",
    "البندقية": "Venice",
    "إسطنبول": "Istanbul",
    "تركيا": "Turkey",
    "دبي": "Dubai",
    "اليابان": "Japan",
    "طوكيو": "Tokyo",
    "دمشق": "Damascus",
    "سوريا": "Syria",

    // Board / Meal options
    "الحجز يشمل وجبة الإفطار اليومية": "Daily Buffet Breakfast Included",
    "حجز غني بالكامل (جميع الوجبات والمشروبات مجاناً)": "All Inclusive High-Tier (Meals & Drinks Cover)",
    "حجز الغرفة فقط بدون وجبات": "Room Only (No Board Included)",
    "Breakfast Included": "Daily Buffet Breakfast Included",
    "All Inclusive (Meals, beverages & private guide) / شامل بالكامل": "VIP All-Inclusive Plan",
    "All Inclusive (Meal & Drinks)": "VIP All-Inclusive Plan",
    "Room Only": "Room Only",

    // Refund Policy Options translations
    "إلغاء مجاني واسترداد كامل قبل 24 ساعة من الوصول": "Free cancellation up to 24 hours before check-in",
    "إلغاء مجاني واسترداد كامل حتى 7 أيام قبل الوصول": "Free cancellation up to 7 days before check-in",
    "غير قابل للاسترداد نهائياً / تطبق رسوم للإلغاء": "Non-refundable booking - No cancellation or refund allowed",
    "مرونة فائقة - تعديل وإلغاء مجاني بأي وقت خلال الإقامة": "Super flexible policy - Modify or cancel free anytime during stay"
  };

  if (translationsMap[str]) {
    return translationsMap[str];
  }

  // Check substring matches
  let current = str;
  Object.keys(translationsMap).forEach(key => {
    if (current.includes(key)) {
      current = current.replace(new RegExp(key, "g"), translationsMap[key]);
    }
  });

  // Arabic characters test
  const hasArabic = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/.test(current);
  if (hasArabic) {
    const arabicToLatin: { [key: string]: string } = {
      'ا': 'a', 'ب': 'b', 'ت': 't', 'ث': 'th', 'ج': 'j', 'ح': 'h', 'خ': 'kh',
      'د': 'd', 'ذ': 'zh', 'ر': 'r', 'ز': 'z', 'س': 's', 'ش': 'sh', 'ص': 's',
      'ض': 'd', 'ط': 't', 'ظ': 'z', 'ع': 'a', 'غ': 'gh', 'ف': 'f', 'ق': 'q',
      'ك': 'k', 'ل': 'l', 'م': 'm', 'ن': 'n', 'ه': 'h', 'و': 'w', 'ي': 'y',
      'أ': 'a', 'إ': 'e', 'آ': 'a', 'ؤ': 'w', 'ئ': 'y', 'ء': 'e', 'ة': 'h', 'ى': 'a',
      ' ': ' '
    };

    const cleanWord = (w: string) => {
      const namesDict: { [key: string]: string } = {
        "أحمد": "Ahmed", "احمد": "Ahmed", "محمد": "Mohamed", "محمود": "Mahmoud",
        "علي": "Ali", "على": "Ali", "حسن": "Hassan", "حسين": "Hussein",
        "سيد": "Sayed", "مصطفى": "Mostafa", "ابراهيم": "Ibrahim", "عمر": "Omar",
        "خالد": "Khaled", "يوسف": "Youssef", "عبد": "Abdel", "الله": "Allah",
        "طه": "Taha", "شريف": "Sherif", "طارق": "Tarek", "هاني": "Hany",
        "عمرو": "Amr", "سعيد": "Said", "سعد": "Saad", "جمال": "Gamal",
        "خليل": "Khalil", "أيمن": "Ayman", "أمير": "Amir", "كريم": "Karim",
        "شادي": "Shady", "هادي": "Hady", "زياد": "Ziad", "سليم": "Selim",
        "فندق": "Hotel", "جناح": "Suite", "غرفة": "Room", "سرير": "Bed",
        "سندباد": "Sindbad", "الاهلي": "Al-Ahli", "الأهلي": "Al-Ahli"
      };
      return namesDict[w] || null;
    };

    const words = current.split(/\s+/);
    const convertedWords = words.map(w => {
      const dictMatch = cleanWord(w);
      if (dictMatch) return dictMatch;
      
      let resWord = "";
      for (let i = 0; i < w.length; i++) {
        const char = w[i];
        if (arabicToLatin[char] !== undefined) {
          resWord += arabicToLatin[char];
        } else {
          resWord += char;
        }
      }
      return resWord.charAt(0).toUpperCase() + resWord.slice(1);
    });

    return convertedWords.join(" ");
  }

  return current;
}

export function generateHotelVoucherPDF(hotel: HotelOption, guest: any, lang: Language) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Pre-configured amenities mapping override to ensure flawless English translation
  const amenitiesMap: { [key: string]: string } = {
    "مسبح بإنفينيتي خارجي مع تدفئة": "Heated outdoor infinity pool",
    "نادي صحي وجلسات يوغا نهارية مجانية": "Prestige health spa & complimentary yoga access",
    "إفطار بوفيه مفتوح كامل": "Full luxurious open-buffet chef breakfast daily",
    "شبكة إنترنت فايبر عالية السرعة ومفتوحة": "Uncapped multi-gigabit fiber Wi-Fi access",
    "غرف مع تراس يطل على حدائق المدينة": "Private terrace suites overlooking landscaped gardens",
    "إلغاء مجاني وحجز مرن": "Fully flexible schedule & complimentary cancelation option",
    "إلطالة بانورامية رائعة على معالم المدينة": "Scenic floor-to-ceiling skyline views",
    "إطلالة بانورامية رائعة على معالم المدينة": "Scenic floor-to-ceiling skyline views",
    "قريب من محطة القطار والمترو (أقل من 3 دقائق)": "Superior proximity walking access to central rail terminal",
    "مطبخ مجهز بالكامل وغسالة ملابس خاصة": "En-suite designer kitchen & private laundry clothes dryer",
    "نظام خدمة شخصية ومرشد محلي خاص للرحلة": "24/7 Personal concierge & customized private travel butler",
    "خدمة استلام وتسليم مجانية بالسيارة من المطار": "Luxury chauffeured airport terminal transfers included"
  };

  const hotelNamesMap: { [key: string]: string } = {
    "منتجع وفندق رويال بالاس الفاخر": "Grand Palace Royal Inn & Resort",
    "فندق ساكورا بوتيك للفنون": "Sakura Boutique Art Space",
    "شقق أوريانتل هافن السكنية الراقية": "Oriental Haven Luxury Suites"
  };

  // Convert inputs using ensureEnglish to guarantee zero non-English character issues
  const safeHotelName = ensureEnglish(hotelNamesMap[hotel.name] || hotel.name).toUpperCase();
  const safeLocation = ensureEnglish(hotel.location);
  const safeGuestName = ensureEnglish(guest.name).toUpperCase();
  const safeRoomType = ensureEnglish(guest.roomType).toUpperCase();
  const safeBoardBasis = ensureEnglish(guest.boardBasis);
  const safeRoomNumber = ensureEnglish(guest.roomNumber || "Suite 402").toUpperCase();
  const safeBookingNumber = ensureEnglish(guest.bookingNumber || "AH-" + Math.floor(100000 + Math.random() * 900000)).toUpperCase();
  const safeCheckIn = ensureEnglish(guest.checkIn);
  const safeCheckOut = ensureEnglish(guest.checkOut);

  // Extract companions and refund policy details safely
  const safeGuest2 = guest.guest2 ? ensureEnglish(guest.guest2).toUpperCase() : "";
  const safeGuest3 = guest.guest3 ? ensureEnglish(guest.guest3).toUpperCase() : "";
  const safeRefundPolicy = ensureEnglish(guest.refundPolicy || "Free cancellation up to 24 hours before check-in");

  let guestCount = 1;
  const companionNameslist: string[] = [];
  if (safeGuest2.trim()) {
    companionNameslist.push(safeGuest2.trim());
    guestCount++;
  }
  if (safeGuest3.trim()) {
    companionNameslist.push(safeGuest3.trim());
    guestCount++;
  }

  // Generate real dynamic barcode & security serial strings
  const rawUUID = Math.floor(10000000 + Math.random() * 90000000).toString();
  const securitySerialCode = `GWA-GDS-REG-991-${safeBookingNumber.replace("AH-", "")}-${rawUUID}-2026-AE-X29`;
  const barcodeValue = `GWA${safeBookingNumber.replace("AH-", "")}V`;

  // Dynamic elite-level hotel contacts mapping
  let hotelPhone = "+33 (0) 1 53 67 19 98"; // Default premium Parisian phone
  let hotelEmail = "concierge.paris@gowithahmed.com";
  
  const hotelLower = safeHotelName.toLowerCase();
  if (hotelLower.includes("dama rose") || hotelLower.includes("rose")) {
    hotelPhone = "+963 (11) 221-5600";
    hotelEmail = "reservations.damarose@gowithahmed.com";
  } else if (hotelLower.includes("four seasons") || hotelLower.includes("seasons")) {
    hotelPhone = "+963 (11) 339-1000";
    hotelEmail = "concierge.damascus@gowithahmed.com";
  } else if (hotelLower.includes("sheraton")) {
    hotelPhone = "+963 (11) 373-8630";
    hotelEmail = "customercare.sheraton@gowithahmed.com";
  } else if (hotelLower.includes("palace") || hotelLower.includes("grand")) {
    hotelPhone = "+33 (0) 1 42 99 80 00";
    hotelEmail = "desk.grandpalace@gowithahmed.com";
  } else if (hotelLower.includes("sakura")) {
    hotelPhone = "+81 (0) 3 3211 5211";
    hotelEmail = "vip.sakuraboutique@gowithahmed.com";
  } else if (hotelLower.includes("haven") || hotelLower.includes("oriental")) {
    hotelPhone = "+44 (0) 20 7589 8288";
    hotelEmail = "leasing.orientalhaven@gowithahmed.com";
  }

  // -------------------------------------------------------------------------
  // THE NEW LUXURY DESIGN LAYOUT: NAVY BLUE (#0F172A) & ELITE GOLD (#C29B38)
  // -------------------------------------------------------------------------

  // 1. Elegant Exterior Page Border Frame (Fine double gold line)
  doc.setDrawColor(194, 155, 56); // Luxury Satin Gold (#c29b38)
  doc.setLineWidth(0.4);
  doc.line(6, 6, 204, 6);
  doc.line(6, 6, 6, 291);
  doc.line(204, 6, 204, 291);
  doc.line(6, 291, 204, 291);

  doc.setDrawColor(226, 232, 240); // Soft grey accent line just inside
  doc.setLineWidth(0.15);
  doc.line(7.2, 7.2, 202.8, 7.2);
  doc.line(7.2, 7.2, 7.2, 289.8);
  doc.line(202.8, 7.2, 202.8, 289.8);
  doc.line(7.2, 289.8, 202.8, 289.8);

  // 2. High-End Dark Header Block (Slate/Navy Blue)
  doc.setFillColor(15, 23, 42); // Midnight slate Navy (#0f172a)
  doc.rect(8, 8, 194, 40, "F");

  // Premium Gold separator line underneath header
  doc.setFillColor(194, 155, 56);
  doc.rect(8, 48, 194, 2.8, "F");

  // Header Title Icons & Typography
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(21);
  doc.text("GO WITH AHMED", 18, 23);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(194, 155, 56); // Saffran gold text
  doc.text("WORLDWIDE ELITE TRAVEL & HOTEL RECEPTIVE NETWORKS", 18, 29.5);

  doc.setFontSize(8);
  doc.setTextColor(180, 190, 210);
  doc.text("Integrated Hotel GDS Confirmation Voucher  |  Automated Check-In Safe ID Document", 18, 36);
  doc.text("Managed for the exclusive portfolio directories of Go with Ahmed Executive Executives.", 18, 40.5);

  // 3. Dynamic Vector Barcode on the Header Group (Saves page space, looks amazing)
  const drawVectorBarcode = (startX: number, startY: number, barcodeStr: string, barcodeHeight = 9) => {
    doc.setFillColor(255, 255, 255);
    doc.rect(startX - 2, startY - 2, 38, barcodeHeight + 6, "F"); // Barcode backdrop white block
    
    doc.setDrawColor(0, 0, 0);
    doc.setFillColor(0, 0, 0);
    doc.setLineWidth(0.35);

    // Iteratively draw custom bar lines representing standard Code39 look
    let xOffset = startX;
    const pattern = [1.2, 0.4, 0.8, 1.6, 0.4, 1.2, 0.4, 0.8, 0.4, 1.2, 1.6, 0.4, 0.8, 0.4, 1.2, 0.4];
    for (let idx = 0; idx < pattern.length; idx++) {
      const width = pattern[idx];
      const isBlack = idx % 2 === 0;
      if (isBlack) {
        doc.rect(xOffset, startY, width, barcodeHeight, "F");
      }
      xOffset += width + 0.5;
    }

    doc.setTextColor(0, 0, 0);
    doc.setFont("courier", "bold");
    doc.setFontSize(7.5);
    doc.text(barcodeStr, startX + 4, startY + barcodeHeight + 3);
  };

  // Draw header barcode
  drawVectorBarcode(154, 13, barcodeValue, 8);

  // 4. Hotel Detail Box Card (No Overflow, padded layout with full contact details)
  let currentY = 58;

  doc.setFillColor(248, 250, 252); // Fine clean snow background
  doc.setDrawColor(226, 232, 240);
  doc.rect(10, currentY, 190, 32, "F"); // Enlarged to accommodate address, phone, and email cleanly

  // Gold vertical sidebar accent
  doc.setFillColor(194, 155, 56);
  doc.rect(10, currentY, 2.5, 32, "F");

  // Hotel Name Text Auto-Shrinking to prevent truncation overflow
  let hotelFontSize = 14;
  if (safeHotelName.length > 30) hotelFontSize = 11.5;
  if (safeHotelName.length > 42) hotelFontSize = 10;
  
  doc.setTextColor(15, 23, 42); // Deep title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(hotelFontSize);
  doc.text(safeHotelName, 17, currentY + 7.5);

  const starSymbol = " " + "★".repeat(hotel.stars || 5) + " LUXURY ACCOMMODATION CATEGORY";
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(194, 155, 56); // Gold star highlights
  doc.text(starSymbol, 17, currentY + 12);

  // Sanitized, clean hotel location row
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.2);
  doc.setTextColor(100, 116, 139);
  let safeAdd = `Physical Address: ${safeLocation}`;
  if (safeAdd.length > 95) {
    safeAdd = safeAdd.substring(0, 92) + "...";
  }
  doc.text(safeAdd, 17, currentY + 18.5);

  // GDS Phone and Email elements
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.8);
  doc.setTextColor(15, 23, 42);
  doc.text("GDS PHONE:", 17, currentY + 25.5);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.2);
  doc.setTextColor(60, 70, 80);
  doc.text(hotelPhone, 38, currentY + 25.5);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.8);
  doc.setTextColor(15, 23, 42);
  doc.text("GDS EMAIL:", 100, currentY + 25.5);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.2);
  doc.setTextColor(60, 70, 80);
  doc.text(hotelEmail.toLowerCase(), 119, currentY + 25.5);

  currentY += 37; // Padded offset for the next layout box

  // 5. STUNNING GRID SECTION FOR RESERVATION & PATRON DETAILS
  doc.setFillColor(252, 252, 253);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  
  // Calculate height needed: base height 58, but if we have companion names we stretch neatly by 7mm per item
  const dynamicGridHeight = 58 + (companionNameslist.length * 6);
  doc.rect(10, currentY, 190, dynamicGridHeight, "F");
  doc.rect(10, currentY, 190, dynamicGridHeight, "S");

  // Grid Horizontal Header banner
  doc.setFillColor(241, 245, 249);
  doc.rect(10, currentY, 190, 8.5, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text("GDS VERIFIABLE RESERVATION RECORD & COMPANION MANIFEST", 15, currentY + 5.5);

  // Real-time security key shown inline for maximum credibility
  doc.setFont("courier", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`HASH ID: ${securitySerialCode.substring(0, 24)}...`, 134, currentY + 5.5);

  // Line separating grid header from rows
  doc.setDrawColor(212, 175, 55); // Rich Gold divider
  doc.setLineWidth(0.45);
  doc.line(10, currentY + 8.5, 200, currentY + 8.5);

  // Custom row plotting algorithms containing boundaries to avoid X overflow
  const printRowField = (label: string, value: string, rowY: number, hasHighlight = false, isRightColumn = false) => {
    const startX = isRightColumn ? 104 : 14;
    const valueX = isRightColumn ? 141 : 52;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.8);
    doc.setTextColor(15, 23, 42);
    doc.text(label, startX, rowY);

    doc.setFont("helvetica", hasHighlight ? "bold" : "normal");
    doc.setFontSize(8.3);
    
    if (hasHighlight) {
      doc.setTextColor(194, 155, 56); // Gold highlighted text
    } else {
      doc.setTextColor(60, 70, 80);
    }

    // Auto truncate values that might extend past columns boundaries
    let cleanVal = String(value).toUpperCase();
    const maxLength = isRightColumn ? 22 : 44; // Increased left length constraint for longer values
    if (cleanVal.length > maxLength) {
      cleanVal = cleanVal.substring(0, maxLength - 3) + "...";
    }
    doc.text(cleanVal, valueX, rowY);
  };

  let rowY = currentY + 14.5;

  // Row 1: Primary Guest Info
  printRowField("LEAD GUEST 1:", safeGuestName, rowY, true);
  printRowField("RESERVATION REF:", safeBookingNumber, rowY, true, true);
  
  rowY += 6.5;

  // Row 2: Dynamic Companion Allocation
  if (companionNameslist.length > 0) {
    printRowField("COMPANION 2:", companionNameslist[0], rowY, false);
  } else {
    printRowField("COMPANION 2:", "N/A - SINGLE PASSENGER", rowY, false);
  }
  printRowField("GDS MASTER ID:", barcodeValue, rowY, false, true);

  rowY += 6.5;

  // Row 3: Dynamic Second Companion Addition
  if (companionNameslist.length > 1) {
    printRowField("COMPANION 3:", companionNameslist[1], rowY, false);
  } else {
    printRowField("COMPANION 3:", "N/A - SINGLE PASSENGER", rowY, false);
  }
  printRowField("ASSIGNED SUITE:", safeRoomNumber, rowY, false, true);

  rowY += 6.5;

  // Row 4: Core Trip Metadata
  printRowField("SUITE CATEGORY:", safeRoomType, rowY, false);
  printRowField("CHECK-IN DATE:", safeCheckIn, rowY, false, true);

  rowY += 6.5;

  // Row 5: Board basis and check-out
  printRowField("MEAL BOARD PLAN:", safeBoardBasis, rowY, false);
  printRowField("CHECK-OUT DATE:", safeCheckOut, rowY, false, true);

  rowY += 6.5;

  // Row 6: Security and Payment State
  printRowField("SECURITY SERIAL:", securitySerialCode, rowY, false);
  printRowField("PAYMENT CLASS:", "PRE-PAID SEAMLESS", rowY, true, true);

  rowY += 6.5;

  // Row 7: Dynamic Total Occupancy & Central Ledger
  printRowField("CENTRAL LEDGER:", "GO WITH AHMED WORLD-GDS", rowY, false);
  printRowField("TOTAL ACTIVE:", `${guestCount} ADULT EXECUTIVES`, rowY, false, true);

  // Row 8: Explicit Refund Policy printed right on the grid frame to fit beautifully!
  rowY += 7.5;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, rowY - 4.2, 196, rowY - 4.2);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.8);
  doc.setTextColor(15, 23, 42);
  doc.text("REFUND RULES:", 14, rowY);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.2);
  doc.setTextColor(180, 50, 40); // Standard security crimson alert color for refund visibility
  
  let formattedRefund = safeRefundPolicy.toUpperCase();
  if (formattedRefund.length > 96) formattedRefund = formattedRefund.substring(0, 93) + "...";
  doc.text(formattedRefund, 38, rowY);

  currentY += dynamicGridHeight + 6;

  // 6. PREMIUM SERVICES AND COMPLIMENTARY VOUCHERING
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("ALL-INCLUSIVE PREMIUM RESORT SERVICES INCLUDED:", 10, currentY);
  currentY += 5.5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.2);
  doc.setTextColor(100, 116, 139);

  // Map amenities beautifully into two parallel compact columns to conserve space and avoid overflow
  const halfLength = Math.ceil(hotel.amenities.length / 2);
  hotel.amenities.forEach((amenity, index) => {
    const rawAmenity = amenity;
    let cleanAmenity = amenitiesMap[rawAmenity] || ensureEnglish(rawAmenity);
    if (cleanAmenity.length > 51) {
      cleanAmenity = cleanAmenity.substring(0, 48) + "...";
    }

    const col = index >= halfLength ? 1 : 0;
    const row = index % halfLength;

    const bulletX = col === 0 ? 12 : 110;
    const bulletY = currentY + row * 5 + 1.25;

    // Golden bullet icon
    doc.setFillColor(194, 155, 56);
    doc.rect(bulletX, bulletY, 1.4, 1.4, "F");

    // Amenity text
    doc.text(cleanAmenity, bulletX + 4, bulletY + 1.25);
  });

  currentY += halfLength * 5 + 7;

  // 7. HIGHLY FORMAL LEGAL RECEPTIVE NOTICE BLOCK (ELEVATED TO MAXIMIZE PROFESSIONAL CREDIBILITY)
  doc.setFillColor(15, 23, 42); // Navy Dark Highlight Block for security regulations
  doc.rect(10, currentY, 190, 36, "F"); // Height slightly pruned to 36 to leave a solid empty gap underneath

  // Bottom gold outline accent on the regulation notice
  doc.setFillColor(194, 155, 56);
  doc.rect(10, currentY + 36, 190, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(194, 155, 56); // Golden header inside block
  doc.text("OFFICIAL SECURITIES CLEARANCE NOTE & BORDER ACCOMMODATION LAWS", 16, currentY + 6.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(220, 225, 235); // Eye-safe tint
  
  const rules = [
    "1. PRESENTATION REQUISITE: Guest must present this official print confirmation and passports upon check-in at hotel desk.",
    "2. MANDATORY CHECKOUT: Standard checkout time is 11:00 AM local zone, compliant with global hotel alliance syndicate pacts.",
    "3. LIABILITY & FEES: Self-verified for simulated layout, testing procedures, and border immigration files compiler system grids.",
    "4. GUARANTEED ADMISSION: Fully supported 2:00 PM Check-In guaranteed by regional travel registries of Go with Ahmed Holding Group.",
    "5. RESERVATION RESTRICTIONS: Cancellations or modification attempts are strictly subjected to the clear policy highlights drawn above."
  ];

  rules.forEach((rule, idx) => {
    doc.text(rule, 16, currentY + 12 + idx * 4.6);
  });

  // 8. LUXURIOUS Dynamic Verification Stamp Seal - Repositioned to a completely spacious empty area below Notice Box to eliminate overlap!
  const sealCenterY = 241;
  const sealCenterX = 168;

  // Print highly authoritative signature and digital certification text on the left of seal
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.2);
  doc.setTextColor(15, 23, 42);
  doc.text("EXECUTIVE DIGITAL AUTHORIZATION & SEAL:", 10, sealCenterY - 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(112, 128, 144);
  doc.text("This secure reservation ID has been electronically signed and authenticated via", 10, sealCenterY + 1.5);
  doc.text("the GWA Global Distributed Syndicate registry protocol. Fully cleared and pre-paid.", 10, sealCenterY + 6);

  // Multi-layered Golden/Navy Seal Circle Stamp
  doc.setDrawColor(194, 155, 56); // Luxurious Golden Seal Outer Ring
  doc.setLineWidth(1.0);
  doc.setFillColor(255, 255, 255); // Solid white backdrop
  doc.circle(sealCenterX, sealCenterY, 13.5, "FD");

  doc.setLineWidth(0.3);
  doc.circle(sealCenterX, sealCenterY, 11, "S");

  doc.setTextColor(15, 23, 42); // Elegant Navy Text inside Seal
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6);
  doc.text("GW AHMED", sealCenterX - 7.5, sealCenterY - 4.5);
  
  doc.setFontSize(7.5);
  doc.setTextColor(194, 155, 56); // Gold "VERIFIED"
  doc.text("VERIFIED", sealCenterX - 6.2, sealCenterY + 1);
  
  doc.setFontSize(5);
  doc.setTextColor(112, 128, 144);
  doc.text("OFFICIAL STAMP", sealCenterX - 6.5, sealCenterY + 6);

  // 9. RE-INVENTED OFFICIAL LONG SERIAL CODE REGISTRY & HUMAN-READABLE BARCODE BLOCK AT FOOTER
  const footerBarcodeY = 265;
  
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(10, footerBarcodeY - 5, 200, footerBarcodeY - 5);

  // Paint dynamic lower barcode
  drawVectorBarcode(82, footerBarcodeY, `SYS-GW-A-${safeBookingNumber.replace("AH-", "")}`, 7.5);

  // Extremely long official GDS System serial registry lines (Provides the highly official long serial requested)
  const systemFullSerial = `SYS-REG-GWA-GDS-CORE-99824-${safeBookingNumber.replace("AH-", "")}-${rawUUID}-2026-ONLINE-SECURE-SSL-AUTHORIZED-GDS-VERIFIED-OK`;
  
  doc.setTextColor(100, 116, 139);
  doc.setFont("courier", "bold");
  doc.setFontSize(7.5);
  doc.text(`SYSTEM REGISTRY SERIAL: ${systemFullSerial}`, 10, footerBarcodeY + 14.5);

  // Standard legal copyright
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(148, 163, 184);
  doc.text("© 2026 Go with Ahmed VIP Travel Syndicate. Document protected by absolute digital SSL encryption key standards. All international covenants apply.", 10, footerBarcodeY + 19);

  doc.save(`HotelVoucher_${safeGuestName.replace(/\s+/g, "_")}.pdf`);
}

// -------------------------------------------------------------------------
// 4. GENERATE FREE ACCESS MUSEUM TICKET PASS
// -------------------------------------------------------------------------
export function generateMuseumPassPDF(museumName: string, visitor: any, lang: Language) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const isAr = lang === "ar";
  
  // Custom design for cultural museums
  doc.setFillColor(153, 27, 27); // Deep Red / Crimson bordeaux #991b1b
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("CULTURAL MUSEUMS CO-ORDINATION VOUCHER", 20, 16);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(isAr ? "بطاقة الدخول الثقافي الموحدة وتذاكر المتاحف المجانية" : "Bilingual Museum Access Permit & Civic Heritage Ticket Pass", 20, 24);

  // Permit Grid
  let currentY = 50;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(153, 27, 27);
  doc.text(museumName.toUpperCase(), 20, currentY);
  currentY += 12;

  doc.setFillColor(248, 250, 252);
  doc.rect(20, currentY, 170, 48, "F");
  doc.setDrawColor(226, 232, 240);
  doc.rect(20, currentY, 170, 48, "S");

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(isAr ? "معلومات بطاقة العبور الثقافي" : "HERITAGE PASS & RECEPTOR INFO", 25, currentY + 8);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(isAr ? `الزائر الرئيسي: ${visitor.name}` : `Lead Visitor Name: ${visitor.name.toUpperCase()}`, 25, currentY + 16);
  doc.text(isAr ? `جواز السفر / الهوية: ${visitor.passport}` : `ID / Passport verification: ${visitor.passport.toUpperCase()}`, 25, currentY + 22);
  doc.text(isAr ? `تاريخ الزيارة المقررة: ${visitor.visitDate}` : `Planned Visit Date: ${visitor.visitDate}`, 25, currentY + 28);
  doc.text(isAr ? `الفترة الزمنية المحددة: ${visitor.visitTime}` : `Reserved Timing Window: ${visitor.visitTime}`, 25, currentY + 34);
  
  const token = "PAS-" + Math.floor(100000 + Math.random() * 900000);
  doc.text(isAr ? `رمز العبور المعتمد: ${token}` : `Museum Entry Ticket Code: ${token}`, 25, currentY + 41);

  // Status Badge box
  doc.setFillColor(220, 38, 38); // Red Pill
  doc.rect(130, currentY + 12, 45, 16, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.text("FREE COORDINATED", 134, currentY + 19);
  doc.text("ADMISSION PASS", 137, currentY + 24);

  currentY += 65;

  // Directions
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(153, 27, 27);
  doc.text(isAr ? "شروط الدخول والامتيازات المشمولة:" : "FREE EXEMPTION CONDITIONS & DIRECTIONS:", 20, currentY);
  currentY += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(isAr 
    ? "البطاقة تعفيك بالكامل من رسوم تذكرة الدخول الأساسية بناءً على الشروط الثقافية للبلد." 
    : "This pass grants complete ticket exemption code based on local civic-education museum agreements.",
    20, currentY
  );
  currentY += 6;
  doc.text(isAr 
    ? "يرجى مسح غلاف التذكرة ببطاقة الهوية السارية عند البوابات الدوارة الذكية للمتحف."
    : "Scan this booking document at the physical tourniquets alongside your official verification identity card.",
    20, currentY
  );
  currentY += 6;
  doc.text(isAr 
    ? "تتضمن البطاقة الدخول لكافة الصالات الدائمة ومعرض التحف التاريخي المدمج."
    : "Benefits encompass standard access to all permanent halls and complementary historic artifacts exhibitions.",
    20, currentY
  );

  currentY += 15;

  // Beautiful visual Ticket Frame decoration with simulated dotted tearing coupon line
  doc.setFillColor(254, 242, 242);
  doc.rect(20, currentY, 170, 32, "F");
  doc.setDrawColor(220, 38, 38);
  doc.setLineWidth(0.4);
  doc.rect(20, currentY, 170, 32, "S");

  drawDashedLine(doc, 135, currentY, 135, currentY + 32, 2, 2);

  // Text inside receipt coupon
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(153, 27, 27);
  doc.text("GATEWAY ACCESS COUPON", 25, currentY + 8);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`Lead: ${visitor.name.toUpperCase()}`, 25, currentY + 16);
  doc.text(`Auth: PASS-VERIFIED`, 25, currentY + 22);

  // Right hand stub info
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("STUB", 145, currentY + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(`TK: ${token}`, 145, currentY + 16);
  doc.text(`HRS: ${visitor.visitTime}`, 145, currentY + 22);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Culture permit generated coordinate network under Eventbrite-Exemption protocols.", 20, 275);

  doc.save(`FreeMuseumTicket_${visitor.name.replace(/\s+/g, "_")}.pdf`);
}
